hpc <- read.csv("~/Coursera/Coursera - Exploratory Data Analysis - R/week1/project 1/Coursera_project1/household_power_consumption.txt", sep=";", stringsAsFactors=FALSE)
str(hpc)
hpc$dateTime <- paste(hpc$Date, hpc$Time, sep= " ")
hpc$dateTime <-strptime(hpc$dateTime, format = "%d/%m/%Y %H:%M:%S")
hpc$Sub_metering_1 <- as.numeric(hpc$Sub_metering_1)
hpc$Sub_metering_2 <- as.numeric(hpc$Sub_metering_2)
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Voltage <- as.numeric(hpc$Voltage)
hpc$Global_reactive_power <- as.numeric(hpc$Global_reactive_power)
plotSample <- subset(hpc, dateTime >= "2007-02-01 00:00:00" & dateTime <= "2007-02-02 23:59:59")
str(plotSample)
with(plotSample, plot(dateTime,Global_active_power, type = "l",xlab = "", ylab = "Global Active Power" ))
with(plotSample, plot(dateTime,Sub_metering_1, type = "l",xlab = "", ylab = "Energy sub metering" ))
lines(plotSample$dateTime ,plotSample$Sub_metering_2, col = "red", type = "l")
lines(plotSample$dateTime ,plotSample$Sub_metering_3, col = "blue", type = "l")
legend("topright", lty = 1, col=c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(plotSample, plot(dateTime, Voltage, type = "l"))
with(plotSample, plot(dateTime, Global_reactive_power, type = "l"))
